python createArticle.py ./content0.txt ../article0.html
python createArticle.py ./content1.txt ../article1.html
python createArticle.py ./content2.txt ../article2.html
python createArticle.py ./content3.txt ../article3.html
python createArticle.py ./content4.txt ../article4.html
python createArticle.py ./content5.txt ../article5.html
python createArticle.py ./content6.txt ../article6.html
python createArticle.py ./content7.txt ../article7.html
python createArticle.py ./content8.txt ../article8.html
python createArticle.py ./content9.txt ../article9.html
python createArticle.py ./content10.txt ../article10.html
